version: "3.9"
services:
  fuseki:
    ## Example:
    ## command: [ "--tdb2", "--update", "--loc", "databases/DB2", "/ds" ]
    command: [ "--tdb2", "--loc", "databases/DB2", "/ds" ]
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JENA_VERSION: 4.6.0
    image: fuseki
    ports:
      - target: 3030
        published: 8080
        protocol: tcp
        mode: host
    volumes:
      # - type: volume
      #   source: logs
      #   target: /fuseki/logs
      # - type: volume
      #   source: databases
      #   target: /fuseki/databases
      - type: bind
        source: ./logs
        target: /fuseki/logs
      - type: bind
        source: ./databases
        target: /fuseki/databases
# volumes:
#   logs:
#   databases: