version: "3.9"
services:
  fuseki:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - target: 3030
        published: ${PORT}
        protocol: tcp
        mode: host
    volumes:
        # 読み込んだデータの永続化ボリュームである
      - type: volume
        source: fuseki-data
        target: /fuseki
        # ロードするRDFファイルを配置するstagingフォルダのバインドマウントである
      - type: bind
        source: ./staging
        target: /staging
    environment:
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      JVM_ARGS: ${JVM_ARGS}
volumes:
  fuseki-data: